### ISSUE TITLE
1.3.5 Broken

### ISSUE THREAD

**Issue by Klowes** [mahjerion/Craft-to-Exile-Harmony-Server#1]
```
C:\Users\Christian\Documents\minecraft servers\CrafttoExile-Harmony-1.3.5-SERVER>java -XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar fabric-server-launch.jar nogui
[11:22:27] [main/INFO]: Loading for game Minecraft 1.16.2
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-3/WARN]: The mod "controlling" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 6 column 9
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-12/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-12/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-14/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[11:22:27] [ForkJoinPool-1-worker-15/WARN]: The mod "cardinal-components-util" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-8/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-8/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-7/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "cardinal-components-chunk" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-11/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-12/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-11/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-12/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-4/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-3/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-4/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-9/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-10/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-3/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-8/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[11:22:27] [ForkJoinPool-1-worker-13/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[11:22:27] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fatxporbs requires {fabricloader @ [>=0.10.6]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:173) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-server-launch.jar:?]
        ... 12 more

C:\Users\Christian\Documents\minecraft servers\CrafttoExile-Harmony-1.3.5-SERVER>pause
Press any key to continue . . .
```

I'm not sure what other info I can give you.

**Comment by mahjerion** [comment]
Hi this is a known issue. I've uploaded the fix but curseforge is being ass and not approving the fix:
![image](https://user-images.githubusercontent.com/66142256/101287408-1fb1ec00-37be-11eb-97c3-7499b080f377.png)

So I ended up unarchiving the "broken" version and included the fix in the changelog... if you read it:
![image](https://user-images.githubusercontent.com/66142256/101287430-3e17e780-37be-11eb-8168-77b8a52775d6.png)

**Comment by mahjerion** [comment]
Unrelated but it's a lot easier for me to find these issues if you post them on the client issue tracker :P thanks for posting though!
